import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="relative z-20 flex items-center justify-between px-8 py-6 lg:px-16 bg-[#121111">
          <div className="text-2xl font-black tracking-tighter uppercase italic text-white">
            Grumpshies<span className="text-purple-500 text-xs">®</span>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
